export const ERROR_CODES = {
  COMMON: {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
  },

  AUTH: {
    INVALID_CREDENTIALS: 401,
    SESSION_EXPIRED: 401,
    EMAIL_ALREADY_EXISTS: 409,
    PASSWORD_TOO_WEAK: 400,
    EMAIL_NOT_VERIFIED: 403,
    ACCOUNT_DISABLED: 403,
    TOO_MANY_LOGIN_ATTEMPTS: 429,
    INVALID_TOKEN: 401,
    MISSING_CREDENTIALS: 400,
  },

  USER: {
    USER_NOT_FOUND: 404,
    USER_FETCH_FAILED: 500,
    PROFILE_UPDATE_FAILED: 500,
    PERMISSION_DENIED: 403,
    ACCOUNT_LOCKED: 403,
    FAILED_TO_DELETE: 500,
  },

  SERVER: {
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
    BAD_GATEWAY: 502,
    REQUEST_TIMEOUT: 408,
    TOO_MANY_REQUESTS: 429,
  },

  VALIDATION: {
    INVALID_EMAIL: 400,
    INVALID_PASSWORD: 400,
    MISSING_FIELD: 400,
    INVALID_FORMAT: 400,
    FIELD_TOO_LONG: 400,
    FIELD_TOO_SHORT: 400,
  },

  QUESTION: {
    QUESTION_NOT_FOUND: 404,
    QUESTION_FETCH_FAILED: 500,
    QUESTION_CREATE_FAILED: 500,
    QUESTION_UPDATE_FAILED: 500,
    QUESTION_DELETE_FAILED: 500,
  },

  SCORE: {
    SCORE_NOT_FOUND: 404,
    SCORE_FETCH_FAILED: 500,
    SCORE_CALCULATE_FAILED: 500,
  },
} as const;

export const SUCCESS_CODES = {
  COMMON: {
    SUCCESS: 200,
    CREATED: 201,
    UPDATED: 200,
    DELETED: 200,
  }
} as const;